config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'links#index'

  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link = Link.find(params[:link_id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @link, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @links = Link.all
  end

  def show
  end

  def new
    @link = current_user.links.build
  end

  def edit
  end

  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :link_id
    = f.number_field :link_id
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th Link
      %th Body
      %th User
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.link_id
        %td= comment.body
        %td= comment.user
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Link:
  = @comment.link_id
%p
  %b Body:
  = @comment.body
%p
  %b User:
  = @comment.user

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RedditClone
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'shared/nav'
    = yield
    = render 'shared/flash_messages'

app/views/links/_form.html.haml
= form_for(@link) do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :url
    = f.text_field :url, class: "form-control"
  .actions
    = link_to 'Back', root_path, class: "btn btn-default"
    = f.submit class: "btn btn-primary pull-right"

app/views/links/edit.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      .form-container 
        %h1 Edit Link
        = render 'form'

app/views/links/index.html.haml
.container
  .link-list
    - @links.each do |link|
      .link-item
        .link-content
          %h1= link_to link.title, link_path(link)
          %p 
            Submitted 
            %strong #{time_ago_in_words(link.created_at)} 
            ago by 
            %strong #{link.user.name}

          = link_to 'View Link', link_path(link), class: "btn btn-primary btn-sm"

        .link-actions
          - if link.user == current_user
            = link_to 'Edit', edit_link_path(link), class: "btn btn-info btn-sm"
            = link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"
          - else 
            = link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do 
              %i.ion-arrow-up-b
              %span Upvote 
              %strong= link.get_upvotes.size
            = link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do 
              %i.ion-arrow-down-b
              %span Downvote 
              %strong= link.get_downvotes.size

app/views/links/new.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      .form-container 
        %h2 Add New Link
        %hr.page-hr
        = render 'form'

app/views/links/show.html.haml
.container
  .link-show-content
    .link-header
      %h2= @link.title
      = link_to "Visit Url", "http://#{@link.url}", class: "btn btn-primary btn-sm"
    .link-actions
      -if @link.user == current_user
        = link_to 'Edit', edit_link_path(@link), class: "btn btn-default"
        = link_to 'Back', links_path, class: "btn btn-default"
      - else 
        = link_to like_link_path, method: :put, class: "btn btn-default btn-sm" do 
          %i.ion-arrow-up-b
          %span Upvote 
          %strong= @link.get_upvotes.size
        = link_to dislike_link_path, method: :put, class: "btn btn-default btn-sm" do 
          %i.ion-arrow-down-b
          %span Downvote 
          %strong= @link.get_downvotes.size

    %hr.page-hr
    %p.comment-count= pluralize(@link.comments.count, "comment")
    %hr.page-hr

    .comment-section
      - @link.comments.each do |comment|
        .comment-item
          %h4= comment.user.name
          %p= comment.body
          .comment-actions
            = link_to 'Delete',[@link, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm"

    .comment-form
      = simple_form_for [@link, Comment.new] do |f|
        = f.text_area :body, class: "form-control"
        = f.submit "Add Comment", class: "btn btn-primary pull-right"

      



    

app/views/shared/_flash_messages.haml
- flash.each do |name, msg|
  = content_tag(:div, msg, class: "alert alert-#{name}")

app/views/shared/_nav.haml
%nav.default-navbar
  .container
    .navi.brand.pull-left
      %h2= link_to 'Le App', root_path
    .navi.links.pull-right
      - if user_signed_in?
        = link_to 'Submit link', new_link_path
        = link_to 'Account', edit_user_registration_path
        = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else 
        = link_to 'Sign up', new_user_registration_path
        = link_to 'Sign in', new_user_session_path